<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="2" ignored="0" total="10" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="FREE CRM Application Test Automation Test Suite" duration-ms="119005" started-at="2020-11-08T06:43:03Z" finished-at="2020-11-08T06:45:02Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="119005" started-at="2020-11-08T06:43:03Z" finished-at="2020-11-08T06:45:02Z">
      <class name="testcases.HomePageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.HomePageTest@54107f42]" name="setUp" is-config="true" duration-ms="11911" started-at="2020-11-08T01:43:36Z" finished-at="2020-11-08T01:43:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="verifyHomepageTitle()[pri:1, instance:testcases.HomePageTest@54107f42]" name="verifyHomepageTitle" duration-ms="52" started-at="2020-11-08T01:43:48Z" finished-at="2020-11-08T01:43:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[HomePAge title not match expected [CRMPR] but found [CRMPRO]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: HomePAge title not match expected [CRMPR] but found [CRMPRO]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at testcases.HomePageTest.verifyHomepageTitle(HomePageTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomepageTitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.HomePageTest@54107f42]" name="tearDown" is-config="true" duration-ms="1074" started-at="2020-11-08T01:43:48Z" finished-at="2020-11-08T01:43:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.HomePageTest@54107f42]" name="setUp" is-config="true" duration-ms="10738" started-at="2020-11-08T01:43:49Z" finished-at="2020-11-08T01:44:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="verifyHomepageTitle()[pri:1, instance:testcases.HomePageTest@54107f42]" name="verifyHomepageTitle" duration-ms="38" started-at="2020-11-08T01:44:00Z" finished-at="2020-11-08T01:44:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[HomePAge title not match expected [CRMPR] but found [CRMPRO]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: HomePAge title not match expected [CRMPR] but found [CRMPRO]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at testcases.HomePageTest.verifyHomepageTitle(HomePageTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomepageTitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.HomePageTest@54107f42]" name="tearDown" is-config="true" duration-ms="1207" started-at="2020-11-08T01:44:00Z" finished-at="2020-11-08T01:44:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.HomePageTest@54107f42]" name="setUp" is-config="true" duration-ms="10205" started-at="2020-11-08T01:44:01Z" finished-at="2020-11-08T01:44:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyHomepageTitle()[pri:1, instance:testcases.HomePageTest@54107f42]" name="verifyHomepageTitle" duration-ms="37" started-at="2020-11-08T01:44:12Z" finished-at="2020-11-08T01:44:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[HomePAge title not match expected [CRMPR] but found [CRMPRO]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: HomePAge title not match expected [CRMPR] but found [CRMPRO]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at testcases.HomePageTest.verifyHomepageTitle(HomePageTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomepageTitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.HomePageTest@54107f42]" name="tearDown" is-config="true" duration-ms="2094" started-at="2020-11-08T01:44:12Z" finished-at="2020-11-08T01:44:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.HomePageTest@54107f42]" name="setUp" is-config="true" duration-ms="10891" started-at="2020-11-08T01:44:23Z" finished-at="2020-11-08T01:44:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyingUserName()[pri:2, instance:testcases.HomePageTest@54107f42]" name="verifyingUserName" duration-ms="370" started-at="2020-11-08T01:44:34Z" finished-at="2020-11-08T01:44:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyingUserName -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.HomePageTest@54107f42]" name="tearDown" is-config="true" duration-ms="1064" started-at="2020-11-08T01:44:35Z" finished-at="2020-11-08T01:44:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.HomePageTest@54107f42]" name="setUp" is-config="true" duration-ms="10885" started-at="2020-11-08T01:44:48Z" finished-at="2020-11-08T01:44:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyContactLink()[pri:3, instance:testcases.HomePageTest@54107f42]" name="verifyContactLink" duration-ms="1954" started-at="2020-11-08T01:44:59Z" finished-at="2020-11-08T01:45:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyContactLink -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.HomePageTest@54107f42]" name="tearDown" is-config="true" duration-ms="949" started-at="2020-11-08T01:45:01Z" finished-at="2020-11-08T01:45:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.HomePageTest -->
      <class name="testcases.LoginPageTest">
        <test-method status="PASS" signature="SetUP()[pri:0, instance:testcases.LoginPageTest@48c40605]" name="SetUP" is-config="true" duration-ms="10332" started-at="2020-11-08T01:43:03Z" finished-at="2020-11-08T01:43:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUP -->
        <test-method status="SKIP" signature="loginPageTitleTest()[pri:1, instance:testcases.LoginPageTest@48c40605]" name="loginPageTitleTest" duration-ms="289" started-at="2020-11-08T01:43:14Z" description="verifying login page title test" finished-at="2020-11-08T01:43:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<CRMPRO - CRM software for customer relationship management, sales, and support.> but was:<CRMPR - CRM software for customer relationship management, sales, and support.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<CRMPRO - CRM software for customer relationship management, sales, and support.> but was:<CRMPR - CRM software for customer relationship management, sales, and support.>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at testcases.LoginPageTest.loginPageTitleTest(LoginPageTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.LoginPageTest@48c40605]" name="tearDown" is-config="true" duration-ms="1977" started-at="2020-11-08T01:43:14Z" finished-at="2020-11-08T01:43:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="SetUP()[pri:0, instance:testcases.LoginPageTest@48c40605]" name="SetUP" is-config="true" duration-ms="6386" started-at="2020-11-08T01:43:16Z" finished-at="2020-11-08T01:43:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUP -->
        <test-method status="SKIP" signature="loginPageTitleTest()[pri:1, instance:testcases.LoginPageTest@48c40605]" name="loginPageTitleTest" duration-ms="108" started-at="2020-11-08T01:43:23Z" description="verifying login page title test" finished-at="2020-11-08T01:43:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<CRMPRO - CRM software for customer relationship management, sales, and support.> but was:<CRMPR - CRM software for customer relationship management, sales, and support.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<CRMPRO - CRM software for customer relationship management, sales, and support.> but was:<CRMPR - CRM software for customer relationship management, sales, and support.>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at testcases.LoginPageTest.loginPageTitleTest(LoginPageTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.LoginPageTest@48c40605]" name="tearDown" is-config="true" duration-ms="1044" started-at="2020-11-08T01:43:23Z" finished-at="2020-11-08T01:43:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="SetUP()[pri:0, instance:testcases.LoginPageTest@48c40605]" name="SetUP" is-config="true" duration-ms="7108" started-at="2020-11-08T01:43:24Z" finished-at="2020-11-08T01:43:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUP -->
        <test-method status="FAIL" signature="loginPageTitleTest()[pri:1, instance:testcases.LoginPageTest@48c40605]" name="loginPageTitleTest" duration-ms="112" started-at="2020-11-08T01:43:31Z" description="verifying login page title test" finished-at="2020-11-08T01:43:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<CRMPRO - CRM software for customer relationship management, sales, and support.> but was:<CRMPR - CRM software for customer relationship management, sales, and support.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<CRMPRO - CRM software for customer relationship management, sales, and support.> but was:<CRMPR - CRM software for customer relationship management, sales, and support.>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at testcases.LoginPageTest.loginPageTitleTest(LoginPageTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.LoginPageTest@48c40605]" name="tearDown" is-config="true" duration-ms="2159" started-at="2020-11-08T01:43:34Z" finished-at="2020-11-08T01:43:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="SetUP()[pri:0, instance:testcases.LoginPageTest@48c40605]" name="SetUP" is-config="true" duration-ms="7508" started-at="2020-11-08T01:44:15Z" finished-at="2020-11-08T01:44:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUP -->
        <test-method status="PASS" signature="LogoImage()[pri:2, instance:testcases.LoginPageTest@48c40605]" name="LogoImage" duration-ms="235" started-at="2020-11-08T01:44:22Z" description="verifying image" finished-at="2020-11-08T01:44:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogoImage -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.LoginPageTest@48c40605]" name="tearDown" is-config="true" duration-ms="988" started-at="2020-11-08T01:44:22Z" finished-at="2020-11-08T01:44:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="SetUP()[pri:0, instance:testcases.LoginPageTest@48c40605]" name="SetUP" is-config="true" duration-ms="7317" started-at="2020-11-08T01:44:36Z" finished-at="2020-11-08T01:44:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUP -->
        <test-method status="PASS" signature="loginTest()[pri:3, instance:testcases.LoginPageTest@48c40605]" name="loginTest" duration-ms="3520" started-at="2020-11-08T01:44:43Z" description="login into app" finished-at="2020-11-08T01:44:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.LoginPageTest@48c40605]" name="tearDown" is-config="true" duration-ms="1752" started-at="2020-11-08T01:44:47Z" finished-at="2020-11-08T01:44:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- FREE CRM Application Test Automation Test Suite -->
</testng-results>
